# Generated by Django 4.0.4 on 2022-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(default='ayo'),
            preserve_default=False,
        ),
    ]
